### ISSUE TITLE
"Embedded subtitle track name u'CC' is not a valid language"

### ISSUE THREAD

**Issue by Coaxial** [caronc/nzbget-subliminal#14]
I am getting this error when scanning MKV files that have embdedded subs:

`2015-10-10 23:58:02,746 - 7871 - ERROR - Embedded subtitle track name u'CC' is not a valid language`

**Comment by caronc** [comment]
You can try scanning again with __-k__ (__--skip-embedded__) which will disreguard any detected subtitles matched.

Does the script just move on (skipping this file - thinking it has subs already) or doe it abort at this point?

**Comment by caronc** [comment]
I looked further into this issue still not having heard back from you (it's been about a month now).  This doesn't appear to be a bug.  What happened was that the video file in question had embedded subtitles in it.  In the language meta field, the individual who encoded the video for you put  **'CC'** in it's language description field (probably intended it to represent **Closed Captioned** which is a bit ambiguous since it doesn't identify the subtitle language itself).  This is where they should have put the actual language code pertaining to the subtitles such as **'en'**, or **'fr'**.  There is no way for Subliminal to know what the language is, so it prints that error and then just moves along treating the video as having containing an unknown subtitle.  This is the intended handling in these situations.

With respect to my first comment, you could force the subs for this by adding the **--skip-embedded** (**-k**) switch and subliminal will ignore these embedded subs and go fetch ones from the internet instead.  This is also an option built into the NZBGet interface if you use it form there.

Good luck.
