### ISSUE TITLE
Encoding doesn't work.

### ISSUE THREAD

**Issue by f3bruary** [caronc/nzbget-subliminal#20]
My turkish, french and arabic subtitles (yes I have lots of Plex friends) are not showing properly. For turkish for example, the source encoding is ISO-8859-9. When I download the file from opensubtitles (http://dl.opensubtitles.org/nl/download/sub/6441695), and encode it myself using 'iconv' on linux, then it seems fine.

Subliminal fetched the same script and even though the encoding function did something, it didn't do it right. The special characters look different than in the original file, but they are still 'garbled'

let me know how I can help to fix this.

**Comment by f3bruary** [comment]
To be clear, I'm trying to encode to utf8

**Comment by caronc** [comment]
This info is perfect, I'm a bit unreliable at this because we just moved. I don't even have internet at the new home yet (2 more days) - responding via cell right now. I will do my best to tackle this when I can, it may be a week or so though.

On a side note, sometimes the subs are in a different encoding then you might think. I mean Turkish subs work with ISO-8859-9 for sure, but if the sub file is already encoded as utf-8 or another type entirely, then forcing it to an alternative might be the problem. Perhaps the bug fix will involve trying to detect the encoding instead of enforcing one. Either way, I'll keep you posted.

**Comment by f3bruary** [comment]
No rush, let me know if I can help

**Comment by caronc** [comment]
I'm getting different output using this newer build of chardet.  It appears a new author has taken over where the old one left off and performed [this pull request](https://github.com/chardet/chardet/pull/41) and [this one too](https://github.com/chardet/chardet/pull/21) which targets your specific issue.

I can't promise this will fix anything; but it's worth a try.  Unfortunately all of our eggs rest in this basket.  I tried to be clever and offer encoding conversion; but it's only as good as this fantastic 'guessing' tool is (the [chardet library](https://github.com/chardet/chardet) itself).

**Comment by f3bruary** [comment]
Not sure if I did something wrong but I'm getting "ImportError: No module named guessit"

**Comment by f3bruary** [comment]
It's still the same for me. Is it working for you ?

**Comment by caronc** [comment]
I'll keep digging; I'm getting mixed results; unfortunately there aren't too many alternatives we can try.

I'm reluctant to learn how chardet works and add a patch mostly because I don't understand the turkish language (at all as English is my primary one). I certainly don't know the Turkish characters, common phases and punctuation that i could key off of either (to patch chardet with)... So i'm the end of the tunnel there.  I can re-open a ticket with them though at the very least. 

[charade](https://github.com/sv24-archive/charade) is an alternative solution but it is no longer maintained (insisting on using chardet instead). [cchardet](https://github.com/PyYoshi/cChardet) for example is another alternative but explicitly documents itself as supporting every format but ISO-8859-9.

What about this solution: What about creating a map of languages to translations?  If someone asks for 'tr' (turkish) subs (as an example), then I'd just assume the file is in ISO-8859-9? It would have to be an optional switch (so you could fall back to the current setup). It would solve your problem (sort of), but it becomes an issue if the file in cases where the file contents are actually in utf-8.

Thoughts?

_I mean the real fix is for all sites to just pick a standard encoding and not mix and match them all.  utf-8, utf-16 or unicode are ideal candidates._

**Comment by f3bruary** [comment]
Have you tried https://code.google.com/archive/p/chared/?

**Comment by caronc** [comment]
No, but let me check it out! It has an lxml requirement, so I'll have to wrap it in try/catch blocks for those who don't have it (fall back to the old way). But it has a turkish encoding entry in it.  It's certainly worth a try!

Thanks for sharing!

**Comment by caronc** [comment]
This latest push may or may not work for you. I integrated chared into subliminal too (I'll push this stuff upstream later to Diaoul after).

The latest chardet doesn't show any real differences; so i'm debating rolling it back.  When fed turkish content; it poops out different (but both invalid) content in both the old and the new version:
```python
import Subliminal.chardet as chardet_new
import chardet as chardet_old
# Read in a turkish file
data=open('tmp2/ORIGINAL.tr.srt', 'rb').read()

# The old spits out the wrong encoding (we know this already - hence this ticket)
chardet_old.detect(data)
{'confidence': 0.876148103338531, 'encoding': 'ISO-8859-2'}

# But the new version is no better; different output entirely too...
chardet_new.detect(data)
{'confidence': 0.7299510001342462, 'encoding': 'windows-1252'}
```

Thanks to your help, here is what chared offers:
```bash
# The output cp1254 converts your file perfectly
# chared is awesome; it just requries the extra knowledge of knowing
# the language we expect to find.  We know this thanks to it being a
# a requirement of Subliminal; so it's really a great suggestion.
./chared -m turkish ../ORIGINAL.tr.srt
../ORIGINAL.tr.srt:    cp1254

# Using the knowledge we can output the file correctly
iconv -f cp1254 -t utf8 ../ORIGINAL.tr.srt > Translated.tr.srt
```
I'm rambling on and on more for a documentation source for me later (paper trail).

This latest push uses chared if it can (if the language is supported by it), if it isn't then it falls back to using chardet (the old way of doing things).  I also fall back to chardet if there is a problem decoding using chared.  Make sense?

Give this last push a test and let me know how your results are!

Chris

**Comment by f3bruary** [comment]
it's still wrong :(

2016-02-05 11:45:50,838 - 5507 - DEBUG - Detecting 'utf_8' (99.999999 confidence) subtitle encoding for Tron Legacy.tr.srt
2016-02-05 11:45:50,849 - 5507 - INFO - Converted Tron Legacy.tr.srt to 'utf-8' encoding.

**Comment by caronc** [comment]
I think the subtitle contents are getting mangled before I apply the chared solution to it. I have another plan :), hopefully I'll have something for you to try before the end of the day (my time). I think our timezones aren't in sync, so you may be waiting another day worst case.

**Comment by f3bruary** [comment]
It's working now. You're the best. Feel free to close if you're done.

**Comment by caronc** [comment]
Great to hear! I'll merge this with the main branch in a bit. :)
