### ISSUE TITLE
Launching script as Post-Processing is detected as cli

### ISSUE THREAD

**Issue by RemyBoyer** [caronc/nzbget-subliminal#27]
Hi,

I have an issue where when adding the script as Post-Processing yields the result `INFO - There were no files found`.

After some digging, this is related to that check : https://github.com/caronc/nzbget-subliminal/blob/master/Subliminal.py#L2119

When launched as Post-Process, NZBGet calls the script with a star `*` argument, which prevents the code from being detected as a post-process, since it sets the `scandir` variable. I don't know why the script is called with this argument. I'm using NZBGet version 18.1.

I've managed to fix it using this:
```
elif len(_args) and _args[0] != '*':
```

Would this fix be accepted as a PR? Or is there something more to it?

**Comment by caronc** [comment]
I can see that ideally you would have expected the asterix (__*__) to substitute itself with all you directory contents;  I'd personally expect that too.  But it's your (operating systems's) shell that is responsible to to do that (not this script). You're intentions are good, but the bug wouldn't be in this script but the shell/program you're executing the script from.. The question is more : "_Why isn't my OS converting the * for me?_.

That said... What operating system are you using? Are you calling this from a cron?  Or from a bash/csh command line manually? Or are you calling it from a windows cmd32 (or maybe even powershell)?

If changing that line works for you in the code; then by all means, leave it that way.  But the easier solution would be to just pass in what the script expects.  Instead of passing in an asterix (__*__) as an argument (that your OS isn't handling for you), pass in  **./** (this current directory) instead.  The script will scan everything in it for you then and no change is required.

There is a python command called [glob()](https://docs.python.org/2/library/glob.html) which i can try to build in support for though if necessary )allowing your asterix to work).  I'll wait for your reply on my other questions before i dig to deep here though.

**Comment by RemyBoyer** [comment]
I'm not actually trying to execute the command myself. NZBGet does.

I just add the the script into the `NZBGet/scripts` folder, add the task as an extension to the category and leave subliminal configuration as default. And it doesn't work, because instead of treating POST-PROCESS as they are, it processes them as if they were a call from the cli, and eventually call the `main()` method instead of `postprocess_main()`. I  don't particularly want anything to understand the `*` as a path expander, I would just like this extension to work :)

Maybe the issue is more related to NZBGet though. I don't understand why a `*` is added as the argument when calling the extension. But as this repo is about the `nzbget + subliminal`, shouldn't it work out of the box?

I'm using NZBGet on Windows.

**Comment by caronc** [comment]
Where in NZBGet are you specifying an Asterix for this Subliminal script? In the Scheduler?

It definitely should just work out of the box; absolutely. If you put the script in the _scripts/_ directory, that's the first part.  The next is to just go into your NZBGet settings, then from the '_EXTENSION SCRIPTS_' on the left hand side, add the script into the list.  You can even use the 'Choose' button on the right to simplify this task.

There is nothing further required. If you want to add a scheduled task to periodically scan your video library, you can do that too from the _Schedule_ section.  But there is no place that I can think of where you would specify an asterix in NZBGet.

**Comment by RemyBoyer** [comment]
I'm not specifying any Asterix anywhere. And as I've said earlier, the issue appears when it's post-processing, not scheduling.

I've setup the extension in the same way to what you've described. I managed to notice the asterix by adding a few logs.

Here are my Subliminal settings. Everything at default, except the language:

```
Subliminal.py:Languages=en, fr
Subliminal.py:Single=yes
Subliminal.py:FetchMode=BestScore
Subliminal.py:SearchMode=advanced
Subliminal.py:SkipEmbedded=yes
Subliminal.py:MinSize=150
Subliminal.py:MinScore=20
Subliminal.py:Providers=opensubtitles, tvsubtitles, podnapisi, addic7ed, thesubdb
Subliminal.py:MovieProviders=
Subliminal.py:TVShowProviders=
Subliminal.py:VideoExtensions=.mkv,.avi,.divx,.xvid,.mov,.wmv,.mp4,.mpg,.mpeg,.vob,.iso
Subliminal.py:ForceEncoding=None
Subliminal.py:SystemEncoding=UTF-8
Subliminal.py:XRefPaths=
Subliminal.py:CacheDir=${TempDir}/subliminal
Subliminal.py:TvCategories=tv, tv2, Series
Subliminal.py:Overwrite=no
Subliminal.py:UpdateTimestamp=yes
Subliminal.py:UpdatePermissions=no
Subliminal.py:VideoPermissions=644
Subliminal.py:ScanDirectories=
Subliminal.py:MaxAge=24
Subliminal.py:Addic7edUser=
Subliminal.py:Addic7edPass=
Subliminal.py:Debug=yes
```

After having made the code change that I've described in the initial comment, I managed to add a Scheduled task too. Now both of them work, thanks to that `elif` condition changed.

This is my task configuration. Nothing fancy here neither.

```
Task1.Time=*:00
Task1.WeekDays=1-7
Task1.Command=Script
Task1.Param=Subliminal.py
```

**Comment by caronc** [comment]
Sorry to be so difficult; you're just the first person to bring this to my attention and the script works great for me.

Let me dig into this deeper and get back to you.  Also, thank you very much for sharing a possible solution! :smile:

**Comment by RemyBoyer** [comment]
Thank *YOU* for taking time to take a closer look 👍 

Let me know if you need info from my environment or if you need me to test something.

**Comment by hugbug** [comment]
Python scripts as you know are not executables and cannot be executed as processes.

On POSIX there is a workaround in form of **shebang**. When a script is passed to a function which creates new processes the system reads the shebang and executes another process instead, while passing the script filename as parameter.

Windows doesn't have shebang thing. Windows Explorer however can execute other processes when double clicked on a file which is not an executable. This works via so called file associations. For a certain file type (typically identified via file extension) the associated program can be defined. The file associations is a pure Windows Explorer thing and not a part of system core.

In order to execute python scripts on Windows NZBGet emulates what Windows Explorer does - it looks in the registry for file associations, finds a program responsible with opening ".py"-files and executes that program (typically python.exe) passing the script filename as parameter. The exact command to execute for certain file type is saved as command string in the registry and can include arbitrary parameters where the filename for script is substituted at any place inside that command string. NZBGet uses system function to embed the script filename into command string. The command string looks like:
```
C:\Program Files (x86)\Python27\python.exe "%1"
```

Here `%1` will be replaced with script filename.

The command string can contain anything at all. For example an asterix:
```
C:\Program Files (x86)\Python27\python.exe "%1" *
```

@RemyBoyer, you can use one of the following methods:
1. Reinstall python to repair py-file association. Make sure to activate installer option which registers py-files.
2. Manually repair the py-file association in the registry.
3. Use option **ShellOverride** in NZBGet.

**Comment by RemyBoyer** [comment]
Hi @hugbug, thank you for this very detailed response.

I've tried uninstalling and reinstalling python on my machine and the behavior remains the same.

I've checked my registry and I have this:

```
Computer\HKEY_CLASSES_ROOT\Python.File\shell\open\command
"C:\Python27\python.exe" "%1" %*
```

This seems to be the normal configuration, as `%*` will expand all other arguments. This configuration is described here: https://docs.python.org/2/using/windows.html#executing-scripts.

I've tried to remove the `%*` and now it actually works! Could this be an issue on how nzbget parses this registry key, misshandling the `%*`?

I've also tried launching a .py file from command line, and I need the `%*` to handle my arguments correctly.

**Comment by hugbug** [comment]
> This seems to be the normal configuration

You are right, indeed.

> Could this be an issue on how nzbget parses this registry key, misshandling the %*?

Yes, that's probably it. It seems it never occurred before as NZBGet scripts usually don't check passed parameters :wink:

NZBGet should remove `%*` from command string.

**Comment by caronc** [comment]
Thank you @hugbug for chiming in.  I was at a loss as i really didn't see where this 'asterix' was coming from. I learned a lot from your explanation as well.

@RemyBoyer : If you're okay with this, i'd prefer not to patch the script at this time. What OS (version of Windows) puts the %* in that registry entry?  Or is this present on all versions?

**Comment by RemyBoyer** [comment]
@caronc I agree that you shouldn't change anything in your script, since the issue seems to come from nzbget

@hugbug Should I create an issue on the nzbget repo? I unfortunately cannot help with the actual bug fix, since I'm not a C++ developer at all

**Comment by hugbug** [comment]
Fixed in nzbget.

@caronc, wouldn't it be better to detect nzbget context by checking presence of one of nzbget env. vars instead of checking command line parameters?

**Comment by caronc** [comment]
@hugbug Yes, i agree. But it just seems strange that this error has only surfaced 3-4 years later into this scripts life.  Is this 'asterix' just part of Windows 10 (or a recent install of Python using a windows installer)? Are all Python scripts called now passed an '*' as an argument? I can see scripts failing and returning that an invalid argument was specified if this is the case. I'm just confused of where this stems from.

That said, I'll still see about enforcing an NZBGet script mode instead of a command line mode if key environment variables are set.

**Comment by RemyBoyer** [comment]
Thanks a lot to both of you!

@caronc I don't think it's anything new nor that it's related to any specific Windows or python version. As @hugbug pointed out, scripts usually don't parse arguments. It was introduced in Subliminal script when you handled this argument as `--scandir`, I suppose. Since then, only the Post-Processing part on Windows failed, which might impact only a few users, since Scheduler could on its side still fetch subtitles.
