### ISSUE TITLE
always skip certain folders

### ISSUE THREAD

**Issue by dlmarston** [caronc/nzbget-subliminal#7]
hi caronc,
i have another use case for you to consider.
i have some tv shows which will never have subtitles created for them, so what if your script could detect the presence of a .subignore file in the directory then skip searching for subtitles for that show?
thanks in advance,
dave

**Comment by caronc** [comment]
I'm both for and against that idea because this can sort of already be done. After a file ages enough (past 24 hours, or whatever you set the variable to), the file will no longer be checked anyway.

So you could technically prevent a future scan from a specific already by waiting the elapsed time, or forcing the elapsed time like so:
```
# Age a file by setting it's date to the year 3032 :)
touch -t 303201010000.00 my.tv.show.that.i.do.not.want.scanned.mkv
```
You could even age it with a simple python script (if your not using a nux based operating system) or if you don't have access to the _touch_ tool.
```python
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
from os import utime
from datetime import datetime
from datetime import timedelta
from time import mktime
import sys

# Offset time 24 hours (or whatever you want)
newtime = datetime.now() + timedelta(hours=24)
# Convert to Epoch
newtime = int(mktime(newtime.timetuple()))
for arg in sys.argv:
    # iterate over each file specified and update it's time
    try:
        utime(arg, (newtime, newtime))
    except OSError:
        # No file; no prob
        print('Sorry, %s was not found.' % arg)
        continue
```
Finally, you can just choose to ignore these files but just not including them in your search:
```bash
# This would look in both paths, for only files and ignore any 
# matches that find the 'special.show' in the title
find /path/to/movies /path/to/series -type f ! -name '*special.show*.*' -exec \
    Subliminal.py -s -S {} \;
```

Your suggestion is good (and would work). The only qualm i have with it is it would only be useful for the first X hours before the show is ignored anyway.  The other thing is, how would you create this .subignore files? Your going to have to have a separate process somewhere on your system that runs before Subliminal.py does just to avoid them being scanned. Would you want these files ignored too even if the __-f__ (__--force__) switch was specified?

Perhaps i could build an __--exclude__ switch into Subliminal that points to a file and/or a series of strings (separated by commas) that contain regular expressions to ignore if matched against? If you specify a file, then I'd parse the file for the regular expressions to apply? This would be a lot of extra work for a very small purpose, but still do-able.

Your thoughts?

**Comment by dlmarston** [comment]
thanks for your response. it prompted me to go back and re-think "why" i want to exclude certain directories. and you gave me the right guidance when you wrote about the age of the files.

i had extended out the elapsed time period in the script i use to run yours. (there is one tv show which gets released two weeks before the subtitles are available). by scaling back the elapsed time to just 24/48 hours (as you have recommended elsewhere), then the shows which don't ever have subtitles would quickly fall out of the scope of the scan.

so maybe you don't need to take any steps at your end and i'll modify at my end.

cheers,

dave

**Comment by caronc** [comment]
Just before i close this ticket, I just wanted to let you know i gave you 'some' faulty information in my previous post.  I was telling you how to set the date in the future 24 hour (or the year 3200 in the touch example).  I just changed that (edits in the previous post were already made) because you want to set these timestamps into the past; not future..  My point was still right; but my examples were way wrong! :)  They've been corrected above; sorry about that!

Chris
